# Generated by Django 5.2.4 on 2025-07-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, choices=[('KENYA', 'KENYA'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('UGA', 'Uganda'), ('USA', 'United States'), ('UK', 'United Kingdom'), ('Canada', 'Canada'), ('India', 'India'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France'), ('Other', 'Other')], default=None, max_length=255),
        ),
    ]
